import Foundation
import Testing
@testable import ghpr

/// Covers block parsing, including GitHub's CRLF line endings.
@Suite("MarkdownBlock")
struct MarkdownBlockTests {
    @Test("a real CRLF PR body parses every heading")
    func realBody() throws {
        let url = try #require(Bundle.module.url(forResource: "pr-body", withExtension: "md", subdirectory: "Fixtures"))
        let body = try String(contentsOf: url, encoding: .utf8)

        let blocks = MarkdownBlock.parse(body)

        let headings = blocks.compactMap { block -> String? in
            if case .heading(_, let text) = block { text } else { nil }
        }
        #expect(headings.contains { $0.hasPrefix("Motivation") })
        #expect(headings.contains { $0.hasPrefix("Modifications") })
        #expect(headings.contains { $0.hasPrefix("Result") })

        for case .paragraph(let text) in blocks {
            #expect(!text.contains("###"), "heading leaked into a paragraph: \(text.prefix(60))")
        }
    }

    @Test("blocks parse: headings, lists, fences, quotes, rules")
    func basics() {
        let text = """
        # Title
        intro line

        - one
        - two

        ```swift
        let x = 1
        ```

        > quoted

        ---
        tail
        """

        let blocks = MarkdownBlock.parse(text)

        #expect(blocks == [
            .heading(level: 1, text: "Title"),
            .paragraph("intro line"),
            .bullets(["one", "two"]),
            .code(language: "swift", text: "let x = 1"),
            .quote("quoted"),
            .rule,
            .paragraph("tail"),
        ])
    }

    @Test("fenced diff keeps its language")
    func diffFence() {
        let text = """
        ```diff
        - old public API
        + new public API
        ```
        """

        #expect(MarkdownBlock.parse(text) == [
            .code(language: "diff", text: "- old public API\n+ new public API")
        ])
    }

    @Test("HTML tables and paragraphs from bots render as blocks")
    func htmlTable() {
        let text = """
        <table>
        <thead>
          <tr>
            <th width="50"></th>
            <th width="100%" data-danger-table="true" data-kind="Warning">
              1 Warning
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>:warning:</td>
            <td data-sticky="false">Big PR</td>
          </tr>
        </tbody>
        </table>

        <p align="right" data-meta="generated_by_danger">
        Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
        </p>
        """

        #expect(MarkdownBlock.parse(text) == [
            .table(header: ["", "1 Warning"], rows: [[":warning:", "Big PR"]]),
            .paragraph("Generated by :no_entry_sign: Danger")
        ])
    }

    @Test("CRLF blank lines still separate paragraphs")
    func crlf() {
        let text = "first\r\n\r\nsecond\r\n### Head\r\nafter"

        let blocks = MarkdownBlock.parse(text)

        #expect(blocks == [
            .paragraph("first"),
            .paragraph("second"),
            .heading(level: 3, text: "Head"),
            .paragraph("after"),
        ])
    }

    @Test("pipe tables parse into header and rows")
    func table() {
        let text = """
        ## SDK Size
        |title|develop|branch|diff|status|
        |-|-|-|-|-|
        |StreamVideo|10.05 MB|10.05 MB|0 KB|🟢|
        |StreamVideoSwiftUI|2.45 MB|2.45 MB|0 KB|🟢|
        """

        let blocks = MarkdownBlock.parse(text)

        #expect(blocks == [
            .heading(level: 2, text: "SDK Size"),
            .table(
                header: ["title", "develop", "branch", "diff", "status"],
                rows: [
                    ["StreamVideo", "10.05 MB", "10.05 MB", "0 KB", "🟢"],
                    ["StreamVideoSwiftUI", "2.45 MB", "2.45 MB", "0 KB", "🟢"],
                ]
            ),
        ])
    }

    @Test("tables with padded separator cells also parse")
    func tableLooseSeparator() {
        let text = """
        | a | b |
        | --- | :-: |
        | 1 | 2 |
        """

        #expect(MarkdownBlock.parse(text) == [
            .table(header: ["a", "b"], rows: [["1", "2"]])
        ])
    }

    @Test("details blocks nest, strip blockquote tags, and keep their summary")
    func details() {
        let text = """
        <!-- This is an auto-generated comment -->
        Intro paragraph.

        <details>
        <summary>🧹 Nitpick comments (1)</summary><blockquote>

        <details>
        <summary>Tests/ScreenSharingView_Tests.swift (1)</summary><blockquote>

        29-37: Use the same background token.

        </blockquote></details>

        </blockquote></details>
        """

        let blocks = MarkdownBlock.parse(text)

        guard blocks.count == 2, case .details(let summary, let inner) = blocks[1] else {
            Issue.record("expected a details block, got \(blocks)")
            return
        }
        #expect(blocks[0] == .paragraph("Intro paragraph."))
        #expect(summary == "🧹 Nitpick comments (1)")

        guard case .details(let nestedSummary, let nestedBlocks) = inner.first(where: {
            if case .details = $0 { true } else { false }
        }) ?? .rule else {
            Issue.record("expected a nested details block, got \(inner)")
            return
        }
        #expect(nestedSummary == "Tests/ScreenSharingView_Tests.swift (1)")
        #expect(nestedBlocks.contains(.paragraph("29-37: Use the same background token.")))
    }

    @Test("multi-line HTML comments disappear")
    func htmlComments() {
        let text = """
        before
        <!-- hidden
        still hidden -->
        after
        """

        // Adjacent lines join into one paragraph, exactly as if the
        // comment lines were never there.
        #expect(MarkdownBlock.parse(text) == [
            .paragraph("before\nafter")
        ])
    }
}
